global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # StatsD Exporter
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']
    scrape_interval: 5s
    metrics_path: /metrics

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API (if it exposes metrics)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: /metrics
    scrape_interval: 10s

  # Frontend (if it exposes metrics)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: /metrics
    scrape_interval: 10s

  # Nginx (if configured with metrics)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /metrics
    scrape_interval: 10s

rule_files:
  # Add alerting rules here if needed
  # - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093