#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker
  - git
  - curl
  - wget
  - unzip
  - snapd

runcmd:
  # Install AWS CLI v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - rm -rf aws awscliv2.zip

  # Install SSM Agent
  - snap install amazon-ssm-agent --classic
  - systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
  - systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service

  # Start and enable Docker
  - systemctl enable docker
  - systemctl start docker
  
  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  
  # Add ec2-user to docker group
  - usermod -a -G docker ec2-user
  
  # Create directory for Docker data
  - mkdir -p /media/prod-dmpfs
  
  # Set up Docker daemon with basic configuration
  - |
    cat > /etc/docker/daemon.json << 'EOF'
    {
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "3"
      }
    }
    EOF
  
  # Restart Docker to apply new configuration
  - systemctl restart docker

# Write a message to the system log
final_message: "System initialization completed at $(date -R)" 